import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/layout/header";

const bYekan = localFont({
  src: "./fonts/YekanBakhFaNum-Regular.woff",
  variable: "--font-Yekan",
  weight: "100 900",
});

const parsKala = localFont({
    src: "./fonts/parskala.ttf",
    variable: "--font-parskaka",
    weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
    <body
        className={`${bYekan.variable} ${parsKala.variable} antialiased`}
    >
    <Header/>
    {children}

    <main>
    </main>
    <div className="overlay"/>

    </body>
    </html>
  );
}
