import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/layout/header";
import Footer from "@/layout/footer";
import ModalContext from "@/context/modal";
import ClientReactQueryProvider from "@/utils/reactQueryProvider-client";
import Auth from "../context/authentication";
import ToastProvider from "@/utils/react-toastify-client";
import NProgressProviders from "@/utils/nprogress-client";
import {GetDynamicLinkPositions, GetDynamicLinkPositionsQuery} from "@/services/DynamicLink";
import {
    dehydrate,
    HydrationBoundary,
} from '@tanstack/react-query'
import {getQueryClient} from "@/utils/get-query-client";
import {Suspense} from "react";

const bYekan = localFont({
    src: "./fonts/YekanBakhFaNum-Regular.woff",
    variable: "--font-Yekan",
    weight: "100 900",
});

const parsKala = localFont({
    src: "./fonts/parskala.ttf",
    variable: "--font-parskaka",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    // const queryClient = getQueryClient()


    // void queryClient.prefetchQuery(GetDynamicLinkPositionsQuery)


    return (
        <html lang="en">
        <body
            className={`${bYekan.variable} ${parsKala.variable} antialiased`}
        >
        <ClientReactQueryProvider>
            <ToastProvider>
                <Auth>
                    <ModalContext>
                        <NProgressProviders>
                                    <Header/>
                                    <main>
                                        {children}
                                    </main>
                                    <Footer/>
                        </NProgressProviders>
                        <div className="overlay"/>
                    </ModalContext>
                </Auth>
            </ToastProvider>
        </ClientReactQueryProvider>
        </body>
        </html>
    );
}
